// packages/react/src/context/KeyboardContextProvider.tsx
import { Keyboard } from '@vgerbot/shortcuts';
import { KeyboardConstructorOptions } from '@vgerbot/shortcuts/lib/foundation/KeyboardConstructorOptions';
import React, { useEffect, useRef } from 'react';
import { KeyboardContext } from './KeyboardContext';
const KEYBOARD_PROPS = Symbol('keyboard-props');

type KeyboardProviderProps =
    React.PropsWithChildren<KeyboardConstructorOptions>;

interface ReactKeyboard extends Keyboard {
    [KEYBOARD_PROPS]: KeyboardProviderProps;
}

export function KeyboardProvider(props: KeyboardProviderProps) {
    const keyboardRef = useRef<ReactKeyboard>();
    if (!keyboardRef.current) {
        keyboardRef.current = new Keyboard(props) as ReactKeyboard;
        keyboardRef.current[KEYBOARD_PROPS] = props;
    }
    useEffect(() => {
        const anchor = keyboardRef.current?.getAnchor();
        if (!props.anchor || anchor === props.anchor) {
            return;
        }
        keyboardRef.current?.setAnchor(props.anchor);
    }, [props.anchor]);
    useEffect(() => {
        if (
            keyboardRef.current &&
            keyboardRef.current[KEYBOARD_PROPS] === props
        ) {
            return;
        }
        keyboardRef.current?.destroy();
        const keyboard = (keyboardRef.current = new Keyboard(
            props
        ) as ReactKeyboard);
        keyboard[KEYBOARD_PROPS] = props;
    }, [props.eventOptions, props.macroRegistry]);
    return (
        <KeyboardContext.Provider value={keyboardRef.current}>
            {props.children}
        </KeyboardContext.Provider>
    );
}

// packages/solid/src/context/KeyboardContextProvider.tsx
import {
    JSXElement,
    ParentProps,
    createEffect,
    createSignal,
    on,
    untrack
} from 'solid-js';
import { KeyboardContext } from './KeyboardContext';
import { Keyboard } from '@vgerbot/shortcuts';

type Options = ConstructorParameters<typeof Keyboard>[0];

type InitKeyboardProviderProps = ParentProps<Options>;

type UserProvideKeyboardProps = ParentProps<{ keyboard: Keyboard }>;

export function KeyboardProvider(props: ParentProps<Options>): JSXElement;
export function KeyboardProvider(
    props: ParentProps<{ keyboard: Keyboard }>
): JSXElement;
export function KeyboardProvider(
    props: InitKeyboardProviderProps | UserProvideKeyboardProps
) {
    if ('keyboard' in props) {
        return (
            <KeyboardContext.Provider value={() => props.keyboard}>
                {props.children}
            </KeyboardContext.Provider>
        );
    } else {
        const [keyboard, setKeyboard] = createSignal(new Keyboard(props));
        createEffect(() => {
            const [eventOptions, macroRegistry] = untrack(() => [
                props.eventOptions,
                props.macroRegistry
            ]);
            const oldKeyboard = keyboard();
            if (oldKeyboard) {
                oldKeyboard.destroy();
            }
            setKeyboard(
                new Keyboard({
                    anchor: props.anchor,
                    eventOptions,
                    macroRegistry
                })
            );
        });
        createEffect(
            on(
                [() => props.eventOptions, () => props.macroRegistry],
                ([eventOptions, macroRegistry]) => {
                    const oldKeyboard = keyboard();
                    if (oldKeyboard) {
                        oldKeyboard.destroy();
                    }
                    setKeyboard(
                        new Keyboard({
                            anchor: props.anchor,
                            eventOptions,
                            macroRegistry
                        })
                    );
                }
            )
        );
        return (
            <KeyboardContext.Provider value={keyboard}>
                {props.children}
            </KeyboardContext.Provider>
        );
    }
}
